* Tutorial Walkthrough URL: https://www.youtube.com/watch?v=GB9ByFAIAH4&feature=youtu.be
* Tutorial Github URL: https://github.com/KeithGalli/NumPy

# NumPy Basics

In [2]:
import numpy as np

### Numpy vs Lists

In [2]:
# Lists
list_a = [1,3,5]
list_b = [2,4,6]
list_a * list_b # Error

TypeError: can't multiply sequence by non-int of type 'list'

In [4]:
# Array of Numpy
import numpy as np

array_a = np.array([1,3,5])
array_b = np.array([1,2,3])
array_a * array_b # Works

array([ 1,  6, 15])

### Initializing Array

In [16]:
a = np.array([1,2,3], dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [7]:
# 2d array of floats
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### The Basics

In [20]:
a

array([1, 2, 3], dtype=int32)

In [21]:
print(a.ndim) # 1 dimension
print(a.shape) # 1 row x 3 columns

1
(3,)


In [22]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [23]:
print(b.ndim) # 2 dimension
print(b.shape) # 2 row x 3 column

2
(2, 3)


In [24]:
# Get Type
a.dtype

dtype('int32')

In [26]:
# Get number of elements
a.size

3

In [27]:
b.size

6

### Accessing/Changing specific elements, rows, columns, etc

In [29]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [30]:
a.shape # 2 x 7

(2, 7)

In [32]:
# Get a specific element [row, column]
# Both row and column are indexing from 0
a[1, 5]

13

In [34]:
# just like list indexing, you can use -2
a[1, -2] 

13

In [35]:
# Get a specific row: 1st row
a[0, :] # 1st row, all the columns

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
# Get a specific column: 3rd column
a[:, 2] # all the row, 3rd column

array([ 3, 10])

In [39]:
# array[FirstRow, StartIndex:EndIndex:StepSize]
a[0, 1:-1:2]

array([2, 4, 6])

In [40]:
# mutating number
print(a)
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [41]:
# mutating column
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3-d example

In [45]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [46]:
b.ndim

3

In [47]:
b.shape

(2, 2, 2)

In [43]:
# Get specific element (wri te outside first, then inside)
b[0,1,1]

4

In [44]:
b[:, 1 ,:]

array([[3, 4],
       [7, 8]])

In [49]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing Different Types of Arrays

In [40]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [50]:
# All 1s matrix
np.ones((2,2), dtype='int32')

array([[1, 1],
       [1, 1]], dtype=int32)

In [44]:
# Filling all values with a number
np.full((2,2), 99) # np.full(shape, value)

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [51]:
# Reusing an array, filling all values with a number (full_like)
print(a)
np.full_like(a, 4)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
# Initializing array with random decimal numbers
np.random.rand(4,2)

array([[0.4322387 , 0.66954166],
       [0.11584211, 0.1368053 ],
       [0.67929478, 0.57301513],
       [0.29090898, 0.31975371]])

In [57]:
# Random Integer values
randint = np.random.randint(-4,8, size=(1,1)) #(StartValue, LimitValue, Shape)
randint

array([[5]])

In [59]:
randint[0][0]

5

In [60]:
# random integer value with numpy
randint_simple = np.random.randint(-4,8, size=1)
randint_simple

array([7])

In [61]:
randint_simple[0]

7

In [76]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [65]:
# Stacking an array by Repeating
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


### Review Question
Make Array Below
```
array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])
```

In [73]:
array_wrapper = np.ones((5,5))
array_wrapper

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [74]:
array_middle = np.zeros((3,3))
array_middle

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [75]:
array_middle[1,1] = 9
array_middle

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [82]:
array_wrapper[1:4,1:4] = array_middle
array_wrapper

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Copy arrays instead of designation!!!

In [90]:
a = np.array([1,2,3])
b = a
b[0] = 100

In [91]:
# b is changed
b

array([100,   2,   3])

In [92]:
# Original a has also changed!
# This is because a and b are pointing the same memory
a

array([100,   2,   3])

In [95]:
a = np.array([1,2,3])
b = a.copy() # NOT b = a
b[0] = 100

a

array([1, 2, 3])

In [96]:
b

array([100,   2,   3])

## Applying calculation to all values in an array

In [97]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [98]:
a + 2

array([3, 4, 5, 6])

In [99]:
a - 2

array([-1,  0,  1,  2])

In [100]:
a * 2

array([2, 4, 6, 8])

In [101]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [102]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [103]:
a ** 2

array([ 1,  4,  9, 16])

In [104]:
# Take the cosine of all the values in array(or matrix)
np.cos(a)



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [117]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [117]:
# Numpy Linear Algebra class' methods
## https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

dir(np.linalg)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

['LinAlgError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_umath_linalg',
 'cholesky',
 'cond',
 'det',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'inv',
 'lapack_lite',
 'linalg',
 'lstsq',
 'matrix_power',
 'matrix_rank',
 'multi_dot',
 'norm',
 'pinv',
 'qr',
 'slogdet',
 'solve',
 'svd',
 'tensorinv',
 'tensorsolve',
 'test']

In [105]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [106]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [108]:
# matrix multiplication (2,3) and (3,2) -> (2,2) matrix
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [111]:
# Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [119]:
# https://youtu.be/GB9ByFAIAH4?t=2611
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [128]:
# minimum value in matrix
np.min(stats) 

1

In [133]:
# minimum value in matrix
np.max(stats)

6

In [129]:
# maximum value
np.max(stats, axis=0) # column basis, or axis = 0

array([4, 5, 6])

In [130]:
# maximum value
np.max(stats, axis=1) # row basis, or axis = 1

array([3, 6])

In [134]:
np.sum(stats, axis=0) # column basis summation

array([5, 7, 9])

### Reorganizing Arrays

In [4]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
before

(2, 4)


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
after = before.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
after = before.reshape((2,2,2))
after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [13]:
# Horizontal  stack
h1 = np.ones((2,4))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
h2 = np.zeros((2,2))
h2

array([[0., 0.],
       [0., 0.]])

In [21]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous
##### Load Data from File

In [26]:
filedata = np.genfromtxt('./data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [27]:
filedata = filedata.astype('int32') # apply values into integer
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


##### Boolean Masking and Advanced Indexing

In [28]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [29]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [23]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [31]:
# indexing with list
a = np.array([10,11,12,13,14])
a[[1,2]] # 1 and 2 are indexing number

array([11, 12])

## Indexing Practice

In [35]:
list_empty = []
matrix = []
for i in range(1,31):
    list_empty.append(i)
    if list_empty[-1]%5 ==0:
        matrix.append(list_empty)
        list_empty=[]

In [36]:
matrix

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25],
 [26, 27, 28, 29, 30]]

In [37]:
matrix = np.array(matrix)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [40]:
# Q1
matrix[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [48]:
# Q2 
matrix[0:4,1:6].diagonal()
# or matrix[0:4,1:].diagonal()

array([ 2,  8, 14, 20])

In [49]:
matrix[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [59]:
matrix[[0,4,5],3:6] 
# or matrix[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])