* official docs: https://numpy.org/doc/stable/user/quickstart.html
* Stanford CS231 CNN for visual recognition: https://cs231n.github.io/python-numpy-tutorial/#numpy
* Scipi Numpy Tutorial: https://www.youtube.com/watch?v=ZB7BZMhfPgk
* (Kor) 팀랩 X 인프런 최성철: https://www.youtube.com/watch?v=aHthqCgsSFs&list=PLBHVuYlKEkULZLnKLzRq1CnNBOBlBTkqp
* (Kor) Zen of Numpy : https://speakerdeck.com/shurain/zen-of-numpy?

## CS231 Tutorial

Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting

## Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3]) # creating rank 1 array
print(type(a)) # print type
print(a.shape) # prints (column numbers, row numbers)
print(a[0], a[1], a[2]) # indexing like list
a[0] = 5 # changing element: elements are mutable like list
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [4]:
column1 = [1,2,3]
column2 = [4,5,6]
b = np.array([column1, column2]) # creating rank 2 array
print(b.shape) # prints (column numbers, row numbers)
print(b[0,0], b[0,1], b[1,0]) # indexing as [column number, row number] where numbers start from 0

(2, 3)
1 2 4


In [5]:
a = np.zeros((2,2)) # 2 x 2 matrix(or array) with all zeros
print(a)

b = np.ones((1,2)) # 1 x 2 matrix, or 1 row 2 column matrix
print(b)

c = np.full((2,2), 7) # 2 x 2 maatrix with a constant value 7
print(c)

d = np.eye(2) # create 2 x 2 identity matrix
print(d)

e = np.random.random((2,2)) # 2 x 2 matrix with random values
print(e)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.37946461 0.83287855]
 [0.35536589 0.45538111]]


## Array indexing
* Numpy offers several ways to index into arrays.
* Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [6]:
import numpy as np

In [11]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):

b = a[:2, 1:3]
b

array([[2, 3],
       [6, 7]])

In [9]:
print(a[0,1])

2


In [11]:
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

77


In [2]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [3]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [4]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [13]:
(x,y) = col_r2.shape
print(x,y)

3 1


In [5]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"


[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [6]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [7]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"


[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


## Datatypes

In [8]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"


int64
float64
int64


## Array math


In [18]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [22]:
# Elementwise sum; both produce the array
# print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]


In [23]:
# Elementwise difference; both produce the array
# print(x - y)
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [25]:
# Elementwise product; both produce the array

# print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]


In [26]:
# Elementwise division; both produce the array
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
# Elementwise square root; produces the array
print(np.sqrt(x))


[[1.         1.41421356]
 [1.73205081 2.        ]]


In [4]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
# print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
# print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# print(x.dot(y))
print(np.dot(x, y))


219
[29 67]
[[19 22]
 [43 50]]


In [5]:
import numpy as np

x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [6]:
print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"


10
[4 6]
[3 7]
