# Array creation routines

## Ones and zeros

In [2]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [3]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [4]:
X = np.array([[1,2,3], [4,5,6]], np.int32)


In [5]:
np.empty_like(X)

array([[         0, 1074266112,          0],
       [1073741824,          0, 1072693248]], dtype=int32)

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [6]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [8]:
np.ones([3,2], float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [9]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)

array([1, 1, 1, 1])

Create a new array of 3*2 float numbers, filled with zeros.

In [10]:
np.zeros([3,2], float)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [11]:
x = np.arange(4, dtype=np.int64)
np.zeros_like(x)

array([0, 0, 0, 0])

Create a new array of 2*5 uints, filled with 6.

In [12]:
np.full([2,5],6,int)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [13]:
x = np.arange(4, dtype=np.int64)
np.ones_like(x)*6
# np.full_like(x,6)

array([6, 6, 6, 6])

## From existing data

Create an array of [1, 2, 3].

In [14]:
np.array([1,2,3])

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [15]:
x = [1,2]
np.array(x)
# or np.asarray(x)

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [16]:
X = np.array([[1, 2], [3, 4]])
np.matrix(X)
# or np.asmatrix(X)

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [17]:
x = [1, 2]
np.asarray(x,float)

array([1., 2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [19]:
x = np.array([30])
x = np.asscalar(x)
x

30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [23]:
x = np.array([1, 2, 3])
y = np.copy(x)
print(id(x), x)
print(id(y), y)

140718171416016 [1 2 3]
140718171415136 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [25]:
x = np.arange(2,101,2)
x

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [28]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
np.diag(X)

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [33]:
x = np.zeros([4,4],int)
for i in range(1,5):
    x[i-1,i-1] = i
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])